services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      # TODO: Move to .env file
      POSTGRES_USER: typless
      POSTGRES_PASSWORD: typless
      POSTGRES_DB: extractordb
    volumes:
      - db-photo-upload-service:/var/lib/postgresql/data
  # database management tool available at http://localhost:8080
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db-photo-upload-service: